# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

from setuptools import find_packages

readme = ""
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, "README.rst")
if os.path.exists(readme_path):
    with open(readme_path, "rb") as stream:
        readme = stream.read().decode("utf8")


setup(
    long_description=readme,
    name="genestboost",
    version="0.1.0",
    description="A generic package to boost any estimator, not just trees",
    python_requires="==3.*,>=3.7.0",
    author="Ben Cross",
    author_email="btcross26@yahoo.com",
    packages=find_packages("src", include=['genestboost', 'genestboost.*']),
    package_dir={"": "src"},
    install_requires=["numpy==1.*,>=1.18.5", "scipy==1.*,>=1.4.1"],
    extras_require={
        "dev": [
            "altair==4.*,>=4.1.0",
            "black==19.*,>=19.10.0.b0",
            "check-manifest==0.*,>=0.42.0",
            "flake8==3.*,>=3.8.3",
            "ipython==7.*,>=7.15.0",
            "isort==4.*,>=4.3.21",
            "jupyter==1.*,>=1.0.0",
            "matplotlib==3.*,>=3.2.1",
            "mypy==0.*,>=0.780.0",
            "pandas==1.*,>=1.0.4",
            "pylint==2.*,>=2.5.3",
            "pytest==5.*,>=5.2.0",
            "pytest-cov==2.*,>=2.10.0",
            "sklearn==0.*,>=0.0.0",
            "sphinx==3.*,>=3.1.1",
            "tox==3.*,>=3.15.2",
            "vega==3.*,>=3.4.0",
        ]
    },
)
